version: '3'

volumes:
  mysql:

services:
  mysql:
    env_file:
      - .env
    container_name: mysql-balance
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "${DB_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql:/var/lib/mysql
      - ./:/var/www
      - ./logs/mysql:/var/log/mysql

  redis:
    env_file:
      - .env
    container_name: redis-balance
    image: redis:latest
    ports:
      - "6379:6379"

  phpmyadmin:
    env_file:
      - .env
    container_name: phpmyadmin-balance
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "3001:80"
    links:
      - mysql