// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: balance.sql

package db

import (
	"context"
)

const getAllBalances = `-- name: GetAllBalances :many
SELECT id, user_id, currency_id, amount FROM balances
`

func (q *Queries) GetAllBalances(ctx context.Context) ([]Balance, error) {
	rows, err := q.db.QueryContext(ctx, getAllBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Balance
	for rows.Next() {
		var i Balance
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CurrencyID,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBalance = `-- name: GetBalance :one
SELECT id, user_id, currency_id, amount FROM balances
WHERE id = ?
`

func (q *Queries) GetBalance(ctx context.Context, id uint64) (Balance, error) {
	row := q.db.QueryRowContext(ctx, getBalance, id)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrencyID,
		&i.Amount,
	)
	return i, err
}
