// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: entry.sql

package db

import (
	"context"
)

const createEntry = `-- name: CreateEntry :execlastid
INSERT INTO entries (balance_id, amount)
VALUES (?, ?)
`

type CreateEntryParams struct {
	BalanceID uint64
	Amount    int64
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createEntry, arg.BalanceID, arg.Amount)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getAllEntries = `-- name: GetAllEntries :many
SELECT id, balance_id, amount FROM entries
`

func (q *Queries) GetAllEntries(ctx context.Context) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, getAllEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(&i.ID, &i.BalanceID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntriesByBalanceID = `-- name: GetEntriesByBalanceID :many
SELECT id, balance_id, amount FROM entries
WHERE balance_id = ?
`

func (q *Queries) GetEntriesByBalanceID(ctx context.Context, balanceID uint64) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, getEntriesByBalanceID, balanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(&i.ID, &i.BalanceID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntryByID = `-- name: GetEntryByID :one
SELECT id, balance_id, amount FROM entries
WHERE id = ?
`

func (q *Queries) GetEntryByID(ctx context.Context, id uint64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntryByID, id)
	var i Entry
	err := row.Scan(&i.ID, &i.BalanceID, &i.Amount)
	return i, err
}

const getLastEntryID = `-- name: GetLastEntryID :one
SELECT id FROM entries
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLastEntryID(ctx context.Context) (uint64, error) {
	row := q.db.QueryRowContext(ctx, getLastEntryID)
	var id uint64
	err := row.Scan(&id)
	return id, err
}
