// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import ()

type Balance struct {
	ID         uint64
	UserID     uint64
	CurrencyID uint64
	Amount     int64
}

type Currency struct {
	ID   uint64
	Name string
}

type Entry struct {
	ID        uint64
	BalanceID uint64
	// can be negative or positive
	Amount int64
}

type Transfer struct {
	ID            uint64
	FromBalanceID uint64
	ToBalanceID   uint64
	// can be only positive
	Amount int64
}

type User struct {
	ID       uint64
	Username string
}
